run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - ireturn
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-blank: true
  funlen:
    lines: 70
  gocognit:
    min-complexity: 30
  gocyclo:
    min-complexity: 10
  nakedret:
    max-func-lines: 0
  goconst:
    min-occurrences: 3

issues:
  exclude-rules:
    - path: main.go
      linters:
        - gochecknoglobals # global in main.go needed for testing
    - path: cmd/
      linters:
        - dupl # CLIs are a lot of similar-looking code!
    - path: _test.go
      linters:
        - dupl # many functions in tests look like duplicates
        - funlen # test function can be very long due to test cases
        - gochecknoglobals # globals in tests are fine
        - gocognit # test functions can be long/complex
    - path: example_*_test.go
      linters:
        - errcheck # not required to check errors in examples
        - ineffassign # not required to check errors in examples
