version: 2

project_name: glen
before:
  hooks:
    - go mod download
builds:
  - id: glen
    binary: glen
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
archives:
  - id: glen
    format: zip
brews:
  - name: glen
    description: A CLI to gather GitLab project and group variables.
    homepage: https://lingrino.com/
    skip_upload: auto
    repository:
      owner: lingrino
      name: homebrew-tap
    directory: Formula
    commit_author:
      name: Sean Lingren
      email: sean@lingren.com
    test: |
      system "#{bin}/glen version"
nfpms:
  - id: glen
    description: A CLI to gather GitLab project and group variables.
    homepage: https://lingrino.com/
    maintainer: "Sean Lingren <sean@lingren.com>"
    license: MIT
    formats:
      - deb
      - rpm
dockers:
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/lingrino/glen:latest
      - ghcr.io/lingrino/glen:{{ .Version }}
      - ghcr.io/lingrino/glen:{{ .Major }}
      - ghcr.io/lingrino/glen:{{ .Major }}.{{ .Minor }}
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
